db.bucket.name: PriceService
db.bucket.password: tesco
db.server.url: http://127.0.0.1:8091/pools

sonetto.shelfUrl : http://ui.tescoassets.com/Groceries/UIAssets/I/Sites/Retail/Superstore/Online/Product/pos/%s.png
sonetto.promotions.data.dump : src/main/resources/com/tesco/services/adapters/sonetto/PromotionsDataExport.xml
sonetto.promotions.xsd : templates/Promotions.xsd

rpm.store.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/STORE_ZONE.csv
rpm.price.zone.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/PRICE_ZONE.csv
rpm.promo.zone.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/PROM_ZONE.csv
rpm.promo.extract.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/PROM_EXTRACT.csv
rpm.promo.desc.extract.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/PROM_DESC_EXTRACT_full_dump.csv


couchbase.nodes:
  - http://127.0.0.1:8091/pools
couchbase.bucket: PriceService
couchbase.username: "PriceService"
couchbase.password: "tesco"
couchbase.admin.username: "Administrator"
couchbase.admin.password: "Tesco123"

couchbase.designdoc.design.name: "prod_designdoc_item"
couchbase.designdoc.view.name: "prod_v_itempurge"
couchbase.designdoc.view.pageno: 10
priceservice.price.last_updated_days: 2

dummyCouchbaseMode: true

hostedGraphite:
  hostname: carbon.hostedgraphite.com
  port: 2003
  apikey: 1d226f2e-fcd0-4eba-8c63-89e11b1ba2d9
  period: 5
http:
  port: 8081
  adminPort: 9081
logging:
  level: INFO
  file:
    enabled: true
    #threshold should be commented/uncommented to enable the logging into log file based on severity required
    threshold: INFO
    #threshold: WARN
    #threshold: ERROR
    currentLogFilename: ./logs/price-service.log
    archivedLogFilenamePattern: ./logs/price-service-%d.log.gz