DBHost: localhost
DBName: priceService
DBPort: 27017
Username:
Password:

rpm.price.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/PRICE_ZONE.csv
rpm.store.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/STORE_ZONE.csv
rpm.promotion.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/PROM_EXTRACT.csv
rpm.promotion_desc.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/PROM_DESC_EXTRACT.csv
sonetto.shelfUrl : http://ui.tescoassets.com/Groceries/UIAssets/I/Sites/Retail/Superstore/Online/Product/pos/%s.png
sonetto.promotions.data.dump : src/main/resources/com/tesco/services/adapters/sonetto/PromotionsDataExport.xml
sonetto.promotions.xsd : templates/Promotions.xsd

rpm.price.zone.data.dump : src/main/resources/com/tesco/services/adapters/rpm/CSVFiles/latest/PRICE_ZONE.csv

hostedGraphite:
  hostname: carbon.hostedgraphite.com
  port: 2003
  apikey: 1d226f2e-fcd0-4eba-8c63-89e11b1ba2d9
  period: 5
http:
  port: 8081
  adminPort: 9081
logging:
  level: INFO
  file:
    enabled: true
    currentLogFilename: ./logs/price-service.log
    archivedLogFilenamePattern: ./logs/price-service-%d.log.gz