DBHost: localhost
DBName: priceService
DBPort: 27017
Username:
Password:
http:
  port: 8081
  adminPort: 9081

logging:
  level: ALL
  file:
    enabled: true
    currentLogFilename: ./logs/price-service.log
    archivedLogFilenamePattern: ./logs/price-service-%d.log.gz